<a href="https://colab.research.google.com/github/sarimiro56/BigData_Python/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%EC%99%80_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape: ', a.shape)
print('a[0]: ', a[0])

b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape: ', b.shape)
print('b[0,0]: ', b[0,0])
print('b[0]: ', b[0])

a.shape:  (4,)
a[0]:  1
b.shape:  (2, 3)
b[0,0]:  1
b[0]:  [1 2 3]


In [2]:
a = np.zeros(2)
print('a\n', a)
b = np.zeros((2,2))
print('b\n', b)
c = np.ones((2,3))
print('c\n', c)
d = np.full((2,3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e)

a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(1, 10, 22)
print(x)
#x = np.arange(1, 11, 0.1)
#print(x)
#y = np.sin(x)
#plt.plot(x, y)

[ 1.          1.42857143  1.85714286  2.28571429  2.71428571  3.14285714
  3.57142857  4.          4.42857143  4.85714286  5.28571429  5.71428571
  6.14285714  6.57142857  7.          7.42857143  7.85714286  8.28571429
  8.71428571  9.14285714  9.57142857 10.        ]


In [8]:
a = np.array([1, 2], dtype=np.float64)
print(a)
print(a.dtype)

#a_i8 = a.astype(np.int8)
#print(a_i8.dtype)

[1. 2.]
float64
