<a href="https://colab.research.google.com/github/sarimiro56/BigData_Python/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%EC%99%80_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape: ', a.shape)
print('a[0]: ', a[0])

b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape: ', b.shape)
print('b[0,0]: ', b[0,0])
print('b[0]: ', b[0])

a.shape:  (4,)
a[0]:  1
b.shape:  (2, 3)
b[0,0]:  1
b[0]:  [1 2 3]


In [2]:
a = np.zeros(2)
print('a\n', a)
b = np.zeros((2,2))
print('b\n', b)
c = np.ones((2,3))
print('c\n', c)
d = np.full((2,3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e)

a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(1, 10, 22)
print(x)
#x = np.arange(1, 11, 0.1)
#print(x)
#y = np.sin(x)
#plt.plot(x, y)

[ 1.          1.42857143  1.85714286  2.28571429  2.71428571  3.14285714
  3.57142857  4.          4.42857143  4.85714286  5.28571429  5.71428571
  6.14285714  6.57142857  7.          7.42857143  7.85714286  8.28571429
  8.71428571  9.14285714  9.57142857 10.        ]


In [10]:
a = np.array([1, 2], dtype=np.float64)
print(a)
print(a.dtype)

a_i8 = a.astype(np.int8)
print(a_i8)
print(a_i8.dtype)

[1. 2.]
float64
[1 2]
int8


In [12]:
arr = np.array([[0, 1, 2], [3, 4, 5]])
print('type(arr):',type(arr))
print('arr.ndim:',arr.ndim)
print('arr.dtype:',arr.dtype)
print('arr.itemsize:',arr.itemsize)
print('arr.size:',arr.size)
print('arr.nbytes:',arr.nbytes)
print('arr.shape:',arr.shape)
print('arr:\n',arr)
print('arr.T:\n',arr.T)
print('arr.shape:',arr.shape)

type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.shape: (2, 3)
arr:
 [[0 1 2]
 [3 4 5]]
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


In [15]:
a = np.arange(8)
print('a\n', a)

a.shape = (2,4)
print('shape\n', a)

print('flatten\n', a.flatten( ))

a.resize((4,2))
print('resize\n', a)
b = a.transpose()
print(b)

a
 [0 1 2 3 4 5 6 7]
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2 4 6]
 [1 3 5 7]]


In [16]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)
b = a.transpose( )
print('b\n', b)
c = a.T
print('c\n', c)

a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]


In [17]:
mask = np.array([0, 1, 1, 0], dtype=bool)
print(mask)
data = np.random.randn(4,2)
print('\ndata 출력\n',data) #랜덤 데이터 배열 data는 책과 다르게 나타남
print('\n마스킹된 데이터 출력\n',data[mask])
print('\n마스킹 역전된 데이터 출력\n',data[~mask])

[False  True  True False]

data 출력
 [[ 0.46972224  0.35779419]
 [ 0.55574292 -1.26072426]
 [ 2.30261075 -0.04701626]
 [-1.28798932 -0.89082364]]

마스킹된 데이터 출력
 [[ 0.55574292 -1.26072426]
 [ 2.30261075 -0.04701626]]

마스킹 역전된 데이터 출력
 [[ 0.46972224  0.35779419]
 [-1.28798932 -0.89082364]]


In [ ]:
posit = data[data > 0]
print('양수 데이터 출력', '\n',posit)

over1 = data[1][data[1] > 0]
print('두 번째 행의 양수 데이터 출력','\n',over1)